# Generated by Django 5.0.6 on 2024-10-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_portfolio',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='company_portfolio',
            name='education',
        ),
        migrations.RemoveField(
            model_name='company_portfolio',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='company_portfolio',
            name='skills',
        ),
        migrations.AddField(
            model_name='company_portfolio',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_portfolio',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_portfolio',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_portfolio',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
