# Generated by Django 5.0.6 on 2024-10-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_remove_company_portfolio_additional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default='ali', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
