# Generated by Django 5.0.6 on 2024-10-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_jobapplication_education_level_jobapplication_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default='talha@gmail.com', max_length=55),
            preserve_default=False,
        ),
    ]
