# Generated by Django 5.0.6 on 2024-10-18 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_jobapplication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.freelancer'),
        ),
    ]
