# Generated by Django 5.0.6 on 2024-10-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_alter_booking_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingroom',
            name='booked_on',
        ),
        migrations.AlterUniqueTogether(
            name='trainingroombooking',
            unique_together={('training_room', 'booking_date', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='trainingroombooking',
            name='booked_duration',
        ),
    ]
