# Generated by Django 5.0.6 on 2024-10-19 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_remove_trainingroom_booked_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingroom',
            old_name='available_from',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='trainingroom',
            old_name='available_to',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='trainingroom',
            name='booking_duration',
        ),
        migrations.RemoveField(
            model_name='trainingroom',
            name='room_number',
        ),
        migrations.AddField(
            model_name='trainingroom',
            name='max_booking_duration',
            field=models.IntegerField(default=2, help_text='Maximum booking duration in hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingroom',
            name='number',
            field=models.CharField(default='2', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrainingBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booking_duration', models.DurationField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.room')),
            ],
        ),
        migrations.DeleteModel(
            name='TrainingRoomBooking',
        ),
    ]
