# Generated by Django 5.0.6 on 2024-10-19 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_rename_available_from_trainingroom_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingbookingrequest',
            name='booking_duration',
        ),
        migrations.AlterField(
            model_name='trainingbookingrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.company'),
        ),
        migrations.AlterField(
            model_name='trainingbookingrequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.trainingroom'),
        ),
        migrations.AlterField(
            model_name='trainingbookingrequest',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
