# Generated by Django 5.0.6 on 2024-10-19 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_remove_trainingbookingrequest_booking_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbookingrequest',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
