# Generated by Django 5.0.6 on 2024-10-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_alter_trainingroom_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_details', models.TextField()),
                ('agreed_by_company', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Pending', max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.adminuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.company')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_details', models.TextField()),
                ('agreed_by_freelancer', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Pending', max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.adminuser')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.freelancer')),
            ],
        ),
    ]
