# Generated by Django 5.0.6 on 2024-10-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_companycontract_freelancercontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontract',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='freelancercontract',
            name='admin',
        ),
    ]
