# Generated by Django 5.0.6 on 2024-10-20 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_remove_companycontract_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontract',
            name='company',
        ),
        migrations.RemoveField(
            model_name='freelancercontract',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='companycontract',
            name='admin',
            field=models.ForeignKey(default='alikhan@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='enroll.adminuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancercontract',
            name='admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='enroll.adminuser'),
            preserve_default=False,
        ),
    ]
