# Generated by Django 5.0.6 on 2024-10-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_remove_companycontract_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontract',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='freelancercontract',
            name='admin',
        ),
    ]
