# Generated by Django 5.0.6 on 2024-10-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0014_remove_companycontract_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.company'),
        ),
        migrations.AddField(
            model_name='freelancercontract',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.freelancer'),
        ),
    ]
