# Generated by Django 5.0.6 on 2024-10-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0015_companycontract_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.company'),
        ),
    ]
