# Generated by Django 5.0.6 on 2024-10-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0016_alter_companycontract_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancercontract',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
