# Generated by Django 5.0.6 on 2024-10-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0017_companycontract_is_global_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancercontract',
            name='is_global',
        ),
    ]
