# Generated by Django 5.0.6 on 2024-10-23 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0018_remove_freelancercontract_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancercontract',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companycontract',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='freelancercontract',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.freelancer'),
        ),
    ]
