# Generated by Django 5.0.6 on 2024-10-23 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0019_freelancercontract_is_global_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontract',
            name='agreed_by_company',
        ),
        migrations.RemoveField(
            model_name='companycontract',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companycontract',
            name='status',
        ),
        migrations.RemoveField(
            model_name='freelancercontract',
            name='agreed_by_freelancer',
        ),
        migrations.RemoveField(
            model_name='freelancercontract',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='freelancercontract',
            name='status',
        ),
        migrations.AddField(
            model_name='companycontract',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='freelancercontract',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CompanyContractResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Pending', max_length=20)),
                ('agreed_by_company', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='enroll.companycontract')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerContractResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Agreed', 'Agreed'), ('Disagreed', 'Disagreed')], default='Pending', max_length=20)),
                ('agreed_by_freelancer', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='enroll.freelancercontract')),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.freelancer')),
            ],
        ),
    ]
