# Generated by Django 5.0.6 on 2024-11-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0020_remove_companycontract_agreed_by_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_portal',
            name='address',
            field=models.CharField(default='rawalakot', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_portal',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
