# Generated by Django 5.0.6 on 2024-12-10 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0024_remove_message_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='company_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_received_messages', to='enroll.company'),
        ),
        migrations.AlterField(
            model_name='message',
            name='company_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_sent_messages', to='enroll.company'),
        ),
    ]
