# Generated by Django 5.0.6 on 2025-01-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0025_message_subject_alter_message_company_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_portfolio',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.company'),
        ),
        migrations.AddField(
            model_name='freelancer_portfolio',
            name='freelancer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.freelancer'),
        ),
    ]
