# Generated by Django 5.0.6 on 2025-01-20 07:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0026_company_portfolio_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='company_recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company_sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='enroll.company'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='enroll.freelancer'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='enroll.company'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='enroll.freelancer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
